### ISSUE TITLE
Display of the eclipse results

### ISSUE THREAD

**Issue by SuAnita520** [mguti97/No-Bells-Just-Whistles#1]
Thank you for sharing such an insightful paper! The methodologies for solving football pitch registration are truly innovative, and I was impressed by the efficiency of the inference process during my tests.

While experimenting with the code, I did encounter a minor issue with the display of the eclipse results

inference.py, Line 130

If I change `pts2` to `pts3`, then my result is correct:
```
XEllipse1 = np.array(pts1, np.int32)
XEllipse2 = np.array(pts2, np.int32)
XEllipse3 = np.array(pts2, np.int32)
frame = cv2.polylines(frame, [XEllipse1], False, (255, 0, 0), 3)
frame = cv2.polylines(frame, [XEllipse2], False, (255, 0, 0), 3)
frame = cv2.polylines(frame, [XEllipse3], False, (255, 0, 0), 3)
```

Before:
![3](https://github.com/user-attachments/assets/3ae35d80-57f5-4141-a28d-b45f34a5e12f)
After:
![3](https://github.com/user-attachments/assets/24f6636b-0af2-4fcc-8979-ac2bdedda4e4)

**Comment by mguti97** [comment]
Thanks for letting me know. Already changed!

**Comment by mguti97** [comment]
Thanks for letting me know. Already changed!
