### ISSUE TITLE
Questions about the line detection

### ISSUE THREAD

**Issue by fmagera** [mguti97/No-Bells-Just-Whistles#2]
Hi @mguti97, 

Thanks for open-sourcing this work, it's really easy to use and super fast 👍 

I have questions about your line detection:
- Would you release your training code ? 
- From your illustration in the paper, I thought that your model predicted also a segmentation of the lines, but from my understanding of your code, you're only predicting the line ends for each of the line classes ?

**Comment by mguti97** [comment]
Hi @fmagera,

As is, the pipeline only extracts line extremities for each of the line classes. However, the output of the line detection model has an extra layer (23 + 1) predicting a pseudo- "edge image" of the lines, but in a pixel-wise Gaussian way. That is the front layer in the illustration. It improves the line detection performance, but It's not used in the pipeline.

About the training code, I was planning on uploading it in mid-September, jointly with the full method extension.

**Comment by fmagera** [comment]
Great! Do you have a snippet code to get this edge image ?

**Comment by mguti97** [comment]
Yeah, It's pretty straightforward:

On the lines corresponding to the line model inference
`heatmaps_l = model_l(image)`

the edge image would correspond to the last layer
`edge_layer = heatmaps_l[:,-1,:,:]`

**Comment by fmagera** [comment]
Thanks :)
