### ISSUE TITLE
mycalib library.

### ISSUE THREAD

**Issue by PajariPy** [mguti97/No-Bells-Just-Whistles#3]
Can't find any mention of it in docs. Internet search also doesn't help. Where to get mycalib library, that is used in data loader?

**Comment by mguti97** [comment]
Sorry, it was the main directory when developing on local. It's just the utils folder from the root directory, already corrected.

**Comment by mguti97** [comment]
Sorry, it was the main directory when developing on local. It's just the utils folder from the root directory, already corrected.

**Comment by PajariPy** [comment]
I appreciate your quick response, thanks. I'm also interested in the training code, because I'm planing to continue your work and improve speed of the model (or, at least, try :) )

**Comment by mguti97** [comment]
We are about to submit an extension of the original pipeline in the next days. As soon as it is submitted, the new pipeline with the changes and the training code will be also uploaded.
